name: product_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.1
  image: ^3.0.1
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
