name: product_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  google_ml_kit: ^0.18.0
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.1
  image: ^3.0.1
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
